/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DeckDeckIdSlideIndexRouteImport } from './routes/deck.$deckId.$slideIndex'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DeckDeckIdSlideIndexRoute = DeckDeckIdSlideIndexRouteImport.update({
  id: '/deck/$deckId/$slideIndex',
  path: '/deck/$deckId/$slideIndex',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/deck/$deckId/$slideIndex': typeof DeckDeckIdSlideIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/deck/$deckId/$slideIndex': typeof DeckDeckIdSlideIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/deck/$deckId/$slideIndex': typeof DeckDeckIdSlideIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/deck/$deckId/$slideIndex'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/deck/$deckId/$slideIndex'
  id: '__root__' | '/' | '/deck/$deckId/$slideIndex'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DeckDeckIdSlideIndexRoute: typeof DeckDeckIdSlideIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deck/$deckId/$slideIndex': {
      id: '/deck/$deckId/$slideIndex'
      path: '/deck/$deckId/$slideIndex'
      fullPath: '/deck/$deckId/$slideIndex'
      preLoaderRoute: typeof DeckDeckIdSlideIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DeckDeckIdSlideIndexRoute: DeckDeckIdSlideIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
