/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as ShellRouteImport } from './routes/_shell'
import { Route as ShellIndexRouteImport } from './routes/_shell.index'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as PresentDeckIdSlideIndexStepIndexRouteImport } from './routes/present.$deckId.$slideIndex.$stepIndex'
import { Route as DeckDeckIdSlideIndexStepIndexRouteImport } from './routes/deck.$deckId.$slideIndex.$stepIndex'

const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellRoute = ShellRouteImport.update({
  id: '/_shell',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellIndexRoute = ShellIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShellRoute,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const PresentDeckIdSlideIndexStepIndexRoute =
  PresentDeckIdSlideIndexStepIndexRouteImport.update({
    id: '/present/$deckId/$slideIndex/$stepIndex',
    path: '/present/$deckId/$slideIndex/$stepIndex',
    getParentRoute: () => rootRouteImport,
  } as any)
const DeckDeckIdSlideIndexStepIndexRoute =
  DeckDeckIdSlideIndexStepIndexRouteImport.update({
    id: '/deck/$deckId/$slideIndex/$stepIndex',
    path: '/deck/$deckId/$slideIndex/$stepIndex',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof ShellIndexRoute
  '/mcp': typeof McpRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/deck/$deckId/$slideIndex/$stepIndex': typeof DeckDeckIdSlideIndexStepIndexRoute
  '/present/$deckId/$slideIndex/$stepIndex': typeof PresentDeckIdSlideIndexStepIndexRoute
}
export interface FileRoutesByTo {
  '/mcp': typeof McpRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/': typeof ShellIndexRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/deck/$deckId/$slideIndex/$stepIndex': typeof DeckDeckIdSlideIndexStepIndexRoute
  '/present/$deckId/$slideIndex/$stepIndex': typeof PresentDeckIdSlideIndexStepIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_shell': typeof ShellRouteWithChildren
  '/mcp': typeof McpRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/_shell/': typeof ShellIndexRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/deck/$deckId/$slideIndex/$stepIndex': typeof DeckDeckIdSlideIndexStepIndexRoute
  '/present/$deckId/$slideIndex/$stepIndex': typeof PresentDeckIdSlideIndexStepIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/mcp'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/.mcp/invoke-tool/$tool'
    | '/deck/$deckId/$slideIndex/$stepIndex'
    | '/present/$deckId/$slideIndex/$stepIndex'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/mcp'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/'
    | '/.mcp/invoke-tool/$tool'
    | '/deck/$deckId/$slideIndex/$stepIndex'
    | '/present/$deckId/$slideIndex/$stepIndex'
  id:
    | '__root__'
    | '/_shell'
    | '/mcp'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/_shell/'
    | '/.mcp/invoke-tool/$tool'
    | '/deck/$deckId/$slideIndex/$stepIndex'
    | '/present/$deckId/$slideIndex/$stepIndex'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ShellRoute: typeof ShellRouteWithChildren
  McpRoute: typeof McpRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
  DeckDeckIdSlideIndexStepIndexRoute: typeof DeckDeckIdSlideIndexStepIndexRoute
  PresentDeckIdSlideIndexStepIndexRoute: typeof PresentDeckIdSlideIndexStepIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell': {
      id: '/_shell'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ShellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell/': {
      id: '/_shell/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ShellIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/present/$deckId/$slideIndex/$stepIndex': {
      id: '/present/$deckId/$slideIndex/$stepIndex'
      path: '/present/$deckId/$slideIndex/$stepIndex'
      fullPath: '/present/$deckId/$slideIndex/$stepIndex'
      preLoaderRoute: typeof PresentDeckIdSlideIndexStepIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deck/$deckId/$slideIndex/$stepIndex': {
      id: '/deck/$deckId/$slideIndex/$stepIndex'
      path: '/deck/$deckId/$slideIndex/$stepIndex'
      fullPath: '/deck/$deckId/$slideIndex/$stepIndex'
      preLoaderRoute: typeof DeckDeckIdSlideIndexStepIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ShellRouteChildren {
  ShellIndexRoute: typeof ShellIndexRoute
}

const ShellRouteChildren: ShellRouteChildren = {
  ShellIndexRoute: ShellIndexRoute,
}

const ShellRouteWithChildren = ShellRoute._addFileChildren(ShellRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  ShellRoute: ShellRouteWithChildren,
  McpRoute: McpRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
  DeckDeckIdSlideIndexStepIndexRoute: DeckDeckIdSlideIndexStepIndexRoute,
  PresentDeckIdSlideIndexStepIndexRoute: PresentDeckIdSlideIndexStepIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
